FLAGSHIP_PROMPT = """
Suggest flagship content that establishes the Persona as an authority based on the provided information.
Utilize the input data, including core value, target audience, persona, and monetization strategy, to brainstorm content ideas.

# Steps

**Analyze Input Data:**
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.

**Generate Content Topics:**
1. Develop 10 content topics that reflect and emphasize the identified core value.
2. Ensure each topic appeals directly to the target audience.
3. Maintain consistency with the persona’s identity, tone, and style, and establish the persona as an authority.
4. Include aspects of the monetization strategy where possible to suggest content that could also drive revenue.

# Output Format
1. Provide a numbered list of 10 flagship content topics.
2. Each topic should be a brief, descriptive sentence or phrase.
"""

FLAGSHIP_REFLECTION_PROMPT = """
Evaluate flagship content topics generated by the FlagshipAgent, focusing on their alignment with business goals and audience targeting.

Use the provided input data:
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.
5. Flagship Content: {flagship_content}

# Steps

1. Identify and select the top 5 flagship content topics that most effectively reflect the persona's expertise.
2. For each selected topic, explain why it aligns with the persona and core values.
3. Propose a unique angle for creating content on each selected topic that would appeal to the target audience.

# Output Format
Provide a structured response listing the top 5 topics, with explanations and unique content angles. Use the following format:
- **Topic 1:** [Topic Name]
  - **Alignment Explanation:** [Reason the topic supports the persona]
  - **Unique Angle:** [Proposed unique content angle]

# Examples
- **Topic 1:** [Improving User Trust]
  - **Alignment Explanation:** This topic showcases the persona's expertise in building relationships, resonating with the core value of reliability.
  - **Unique Angle:** Incorporate real-life testimonials and success stories to engage the target audience of small business owners.

# Notes
1. Ensure each explanation of topic alignment clearly reflects the relationship between the topic and the persona.
2. The unique content angles should be creative but realistic within the context of the persona and audience.
"""

SEASONAL_PROMPT = """
Identify Holidays and Seasonal Events to support content brainstorming.

# Steps

**Analyze Input Data:**
Input Data:
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.

**Identify Holidays and Seasonal Events:** 
Determine relevant holidays and seasonal events that align with the industry, persona, and audience specific to the input data.

# Output Format

1. Provide a numbered list of holidays and seasonal events.
2. Each event should be listed as a brief, descriptive sentence or phrase.

# Examples

**Input Data**
1. Core Value: Sustainability
2. Target Audience: Eco-conscious consumers
3. Persona: Millennial urban professionals
4. Monetization Strategy: Subscription service

**Output**
1. Earth Day - A global event celebrated to demonstrate support for environmental protection.
2. World Environment Day - Engages raising awareness and action for the environment.
3. Arbor Day - Encourages individuals to plant and care for trees.

# Notes
1. Real examples should include but not limited to national holidays.
2. The output might be longer with more detailed descriptions, directly tied to the provided input data.
"""

SEASONAL_CONTENT_PROMPT = """
Suggest seasonal content ideas based on holidays and seasonal events to support content brainstorming.
Consider the core values, target audience, persona, and monetization strategy provided to create relevant and engaging content ideas 
that align with the brand's goals and connect with the audience effectively.

# Steps

**Analyze Input Data:**
Input Data:
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.

**Identify Holidays and Seasonal Events:** 
1. For each holiday or events genereted by the SeasonalEventAgent, brainstorm unique angles and content ideas that cater to the target audience 
and align with the brand's persona and monetization strategy.

# Output Format
1. Provide a list of seasonal content topics paired with unique angles for content creation.
2. Each topic should include a brief explanation of how it appeals to the target audience.
3. Structure the output as a series of bullet points or numbered list items with clear separation between different holidays or events.

# Examples

**Input Data Example:**
- Core Value: Sustainability
- Target Audience: Eco-conscious millennials
- Persona: Friendly and informative
- Monetization Strategy: Subscription for eco-friendly products

**Output Example:**
1. **Earth Day:**
   - Topic: "How to Celebrate Earth Day with Sustainable Lifestyle Choices"
   - Angle: Create an interactive blog post featuring a quiz on carbon footprint reduction and highlight eco-friendly products available through the subscription service.

2. **Summer Solstice:**
   - Topic: "Eco-Friendly Summer Solstice Celebrations"
   - Angle: Develop a video series on crafting DIY solar lanterns at home, aligned with an exclusive offer on eco-friendly kits.

(Real examples should be tailored with specific holidays/events relevant to the business or locale.)

# Notes

1. Ensure each content idea is targeted and relevant to the specified audience and supports the business's monetization strategy effectively.
2. Be mindful of cultural sensitivity and appropriateness for the selected holidays and events.
3. Consider local and global holidays depending on the brand’s reach and target audience.

"""

EVERGREEN_PROMPT = """
Suggest evergreen content that is always relevant no matter what year it is based on the provided information.
Utilize the input data, including core value, target audience, persona, and monetization strategy, to brainstorm content ideas.

# Steps

**Analyze Input Data:**
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.

**Generate Content Topics:**
1. Identify themes relevant to the core value that appeal to the target audience and suit the persona.
2. Brainstorm content topics that align with the monetization strategy and enhance audience engagement.
3. For each topic, propose an angle that emphasizes the importance of the content and connects with the audience's preferences or needs.

# Output Format
1. Provide a numbered list of 10 evergreen content topics.
2. Each topic should be a brief, descriptive sentence or phrase.
3. Propose a unique angle for creating content on each selected topic that would appeal to the target audience.

# Examples

**Input Data Example:**
- Core Value: Sustainability
- Target Audience: Eco-conscious millennials
- Persona: Friendly and informative
- Monetization Strategy: Subscription for eco-friendly products

**Output Example:**
1. "Sustainable Living Hacks: Everyday Tips for Eco-Warriors" 
- Angle: Focus on practical, cost-effective ideas that can be implemented easily by millennials in their daily routines.
2. "The Ultimate Guide to Eco-Friendly Shopping" 
- Angle: Highlight popular, high-quality brands and products that align with sustainability values, making it a go-to resource for subscribers.
3. "Zero Waste Lifestyle: A Beginner’s Journey" 
- Angle: Share a relatable personal or community story showcasing the journey towards zero waste, making it an inspiring read for those curious about sustainability.

# Notes
1. Always ensure the content is informative, engaging, and reflects the specified persona.
2. Consider the long-term value and searchability of the content to remain relevant across years.
3. Align topics with current interests, technological advances, and cultural trends to maintain content engagement over time.

"""

Edit_PROMPT = """
You are a skilled content editor, crafting concise and accurate reports.  Your task is to summarize the provided content into a structured report, 
focusing on the key information presented for each content type.

**Brand Information:**
1. Core Value: {core_value_provided} - The primary value or benefit the business/service offers.
2. Target Audience: {target_audience} - The specific group of people the business is targeting.
3. Persona: {persona} - The public-facing image or identity the business/brand adopts, including tone and style.
4. Monetization Strategy: {monetization} - The products or services sold or the strategy for generating revenue.

**Content Summary:**

**Flagship Content:**
{flagship_content}

**Seasonal Content:**
{seasonal_content}

**Evergreen Content:**
{evergreen_content}

**Instructions:**
Create a structured report that **specifically summarizes** the provided Flagship, Seasonal, and Evergreen content.  
Do not generate new content or examples.  Focus on extracting and presenting the most important information from each section.

Your report should include:

* **Introduction:** Briefly introduce the purpose of the report (to summarize the provided content) and explain what the Flagship, Seasonal, and Evergreen content are.
* **Flagship Content Summary:**  Concisely summarize the key points of the flagship content.
* **Seasonal Content Summary:** Concisely summarize the key points of the seasonal content.
* **Evergreen Content Summary:** Concisely summarize the key points of the evergreen content.
* **Conclusion:** Briefly conclude the report by reiterating the types of content summarized.

Maintain a clear, concise, and objective tone throughout the report.  Prioritize accuracy and conciseness over creativity or elaboration.
"""